### ISSUE TITLE
Create inital concept (Sprint 1)

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#1]
Toost-cloud is a lightweight cloud solution for small companies or private indivudals. Our main feature is a synced and easy to use file managment system, that is self hosted.

**Sprint 1**

- [ ] Create Ionic scaffold (#2 )
- [ ] Create Quarkus (native) scaffold (#4)
- [ ] JWT Authentication and authorization (#11)
- [ ] Write basic docker files + uploading first version on docker hub
- [ ] Write basic CI flow for backend (#3)
- [ ] Write basic CI flow for frontend (#5)
- [ ] Wrap all CI flows (blocked by the two above) (#6)
- [ ] Write basic tests for backend (#26)
- [ ] Write basic tests for frontend (#27)
- [ ] Write ReadMe (root) (#7)
- [ ] Write frontend ReadMe (#8)
- [ ] Write backend ReadMe (#9)
- [ ] Write kubernetes files (#10)
- [ ] Research why TailwindCSS styles are not rendered in IOS app (#13)
- [ ] Setup Codacy for the frontend (#14)
- [ ] Setup Codacy for the backend (#15)

**Comment by benediktkaiser** [comment]
Initial Sprint one is done. All open issues moved to Sprint 2
