### ISSUE TITLE
Write basic backend tests

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#26]
**Goals**
Have a simple testing suit that can be easily expanded once more tests are needed.

**Tasks**

- [ ] Configure the boilerplate for a testing suite
- [ ] Write a few demo tests
- [ ] Have the tests be executed in the CI workflow and Merge workflow

Tests:
- Integration Tests (for all endpoints)
- Unit Tests for business logic

**Comment by ReaperMaga** [comment]
Already done in #34
