### ISSUE TITLE
Clean up `web-app` repository

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#28]
**Goal**
Remove unneded frontend files that we will not be using.

**Tasks**

- [x] Remove StoryBook examples
- [x] Write one simple Storybook example to use
- [x] Remove boilerplate code
- [x] Make a placeholder start page
