### ISSUE TITLE
Write basic CI flow for backend

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#3]
**Goal**
We need a working CI for the backend. Create the new CI flow with all steps we need to verfiy the code.

**Tasks**

- [ ] Create the new Workflow in `./github`
- [ ] Write a pull request workflow
- [ ] Write a merge workflow

Call the flow **CI/backend**
