### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#43]
Toost-cloud is a lightweight cloud solution for small companies or private indivudals. Our main feature is a synced and easy to use file managment system, that is self hosted.

**Sprint 2**

- [ ] Add MobX to the Project
- [ ] Add Theme switcher to Header
- [ ] Basic file upload/download (Backend)
- [ ] Basic file upload flow (frontend)
- [ ] Connect frontend and backend file upload flows
- [ ] Design search bar for the header
- [ ] Design login screen
- [ ] Design setup wizzard
- [ ] Create setup endpoint
- [ ] Implement login functionality (frontend)
- [ ] Add frontend readme (#8)
- [ ] Added backend readme (#9)
- [ ] Create API docs (add to backend readme?)
- [ ] Add configuration handling (config files)
- [ ] Implement simple page switching tests
- [ ] Write frontend tests (#27)
