### ISSUE TITLE
Add Sidebar Layout

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#44]
**Goal**
Add a layout option with a sidebar and header

**Content**
Design the sidebar and header. They do not need to be functional. Please also create a dark mode option.

**Tasks**

- [ ] Create the simple layout
- [ ] Design the sidebar (light + dark)
- [ ] Design the Header (light + dark)
- [ ] Design top toolbar
- [ ] Write stories to show all the new components
