### ISSUE TITLE
Write root ReadMe

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#7]
**Goal**
Write a Readme that explains our project and our goals. Give some example usages and leave space for instructions for downloading and self hosting.

**Tasks**

- [ ] Write a simple project description
- [ ] Add steps to installation
- [ ] Add license reference
- [ ] Design new Assets to use in order to make it more appealing

(any more? @ReaperMaga)
