### ISSUE TITLE
Write frontend ReadMe

### ISSUE THREAD

**Issue by benediktkaiser** [toost-net/toost-cloud#8]
**Goal**
Write a ReadMe for the frontend, explaining what it is how to use it and how to develop it.

**Tasks**

- [ ] Give a brief project explanation
- [ ] Explain how to start the project in Dev mode
- [ ] Add any extra infos needed to develop the system
